# Generated by Django 3.1.6 on 2021-06-23 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('d_address', models.TextField(default='')),
                ('d_contact', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('d_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_received', models.CharField(blank=True, default='', max_length=75, null=True)),
                ('r_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('r_quantitydescription', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('item_status', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('r_contact', models.PositiveIntegerField(blank=True, default='', null=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('r_address', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('Very Satisfied', 5), ('Satisfied', 4), ('Neutral', 3), ('Disssatisfied', 2), ('Very Disssatisfied', 1)], default='Neutral')),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('Suggestions', models.TextField(blank=True, default='', null=True)),
                ('rdetails_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiverinfo')),
                ('rdetails_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiveddonations')),
            ],
        ),
        migrations.AddField(
            model_name='receiveddonations',
            name='received_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiverinfo'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=75, null=True)),
                ('quantity_no', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity_description', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('date_donated', models.DateField(blank=True, null=True)),
                ('donator_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.donatorinfo')),
            ],
        ),
    ]
