# Generated by Django 3.1.6 on 2021-05-22 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(default='', max_length=100)),
                ('r_contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('r_address', models.TextField(default='')),
                ('r_affiliation', models.CharField(choices=[('ALUMNI', 'Alumni'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('NONE', 'None')], default='NONE', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_received', models.CharField(default='', max_length=75)),
                ('r_quantity', models.PositiveIntegerField(default=0)),
                ('r_quantitydescription', models.CharField(default='', max_length=10)),
                ('item_status', models.CharField(default='', max_length=30)),
                ('date_received', models.DateField()),
                ('received_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiverinfo')),
            ],
        ),
    ]
