# Generated by Django 3.1.6 on 2021-06-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPantry', '0002_auto_20210623_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveddonations',
            name='received_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiverinfo'),
        ),
    ]
