# Generated by Django 3.1.6 on 2021-06-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPantry', '0003_auto_20210623_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverfeedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[('Very Satisfied', 5), ('Satisfied', 4), ('Neutral', 3), ('Disssatisfied', 2), ('Very Disssatisfied', 1)], default='Neutral', null=True),
        ),
        migrations.AlterField(
            model_name='receiverfeedback',
            name='rdetails_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiverinfo'),
        ),
        migrations.AlterField(
            model_name='receiverfeedback',
            name='rdetails_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityPantry.receiveddonations'),
        ),
    ]
