# Generated by Django 3.1.6 on 2021-06-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPantry', '0004_auto_20210624_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiverfeedback',
            name='rating',
        ),
    ]
